name: "Stale Labeler"
on:
  schedule:
    - cron: "0 00 * * *"   # <=== Change this value

jobs:
  labeler:
    name: Label Stale Things
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Srvaroa Labeler"
        uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config_path: .github/stale_labeler.yml
          fail_on_error: true
